/**
 * Human-facing browser chrome injected into the top-level page document.
 * Keeping this UI in the page renderer avoids a second Electron
 * WebContentsView and leaves the host composition tree stable.
 */
export const PAGE_CHROME_HOST_ID = '__dsh_browser_chrome_host__';
export const PAGE_CHROME_ATTRIBUTE = 'data-dsh-browser-chrome';
/** Generated once; stable across documents and reused by the provider. */
export const PAGE_CHROME_SCRIPT = buildPageChromeScript();
/** Convert human address-bar text into an allowed HTTP(S) navigation target. */
export function normalizeBrowserAddress(raw) {
    const value = raw.trim();
    if (value === '')
        return '';
    if (/^https?:\/\//i.test(value))
        return value;
    if (/^[a-z][a-z0-9+.-]*:/i.test(value))
        return '';
    if (value.includes(' ') || !value.includes('.')) {
        return 'https://www.bing.com/search?q=' + encodeURIComponent(value);
    }
    return 'https://' + value;
}
/** Build a self-contained CDP page-start script. */
export function buildPageChromeScript() {
    const normalizer = normalizeBrowserAddress.toString();
    const toolbarHtml = [
        '<style>',
        '#bar { position:absolute; top:8px; left:50%; transform:translateX(-50%); box-sizing:border-box; width:min(940px,calc(100vw - 24px)); min-height:40px; display:flex; align-items:center; gap:6px; padding:5px 7px; border:1px solid rgba(255,255,255,.14); border-radius:10px; background:rgba(24,26,31,.95); box-shadow:0 8px 28px rgba(0,0,0,.32); color:#edf0f4; font:13px system-ui,sans-serif; pointer-events:auto; }',
        'button { width:30px; height:28px; border:0; border-radius:6px; background:transparent; color:inherit; cursor:pointer; font:18px/1 system-ui,sans-serif; }',
        'button:hover { background:rgba(255,255,255,.13); }',
        'button:active { transform:scale(.9); }',
        '#bar button svg { display:block; margin:auto; }',
        '#bar button.spinning { animation:dshSpin .5s linear; }',
        '@keyframes dshSpin { to { transform:rotate(360deg); } }',
        'button:active { transform:scale(.9); }',
        '#bar button svg { display:block; margin:auto; }',
        '#bar button.spinning { animation:dshSpin .5s linear; }',
        '@keyframes dshSpin { to { transform:rotate(360deg); } }',
        '#address { box-sizing:border-box; flex:1; min-width:80px; height:28px; padding:0 11px; border:1px solid rgba(255,255,255,.15); border-radius:14px; outline:none; background:rgba(0,0,0,.25); color:inherit; font:inherit; }',
        '#address:focus { border-color:#67a1ff; box-shadow:0 0 0 2px rgba(103,161,255,.24); }',
        '#panel { position:absolute; top:48px; left:50%; transform:translateX(-50%); box-sizing:border-box; width:min(420px,calc(100vw - 24px)); max-height:320px; overflow:auto; display:none; border:1px solid rgba(255,255,255,.14); border-radius:10px; background:rgba(24,26,31,.97); box-shadow:0 12px 36px rgba(0,0,0,.45); padding:8px; color:#edf0f4; font:13px system-ui,sans-serif; pointer-events:auto; }',
        '#panel.open { display:block; }',
        '#panel .save { width:auto; padding:0 12px; height:30px; border:1px solid rgba(255,255,255,.15); border-radius:6px; background:rgba(103,161,255,.18); color:#cfe0ff; font:13px system-ui,sans-serif; cursor:pointer; }',
        '#panel .item { display:flex; align-items:center; gap:8px; padding:7px 9px; border-radius:6px; cursor:pointer; }',
        '#panel .item:hover { background:rgba(255,255,255,.09); }',
        '#panel .item .t { flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
        '#panel .item .u { color:#8fb2ff; font-size:11px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; max-width:180px; }',
        '#panel .item .x { width:24px; height:24px; font:14px/1 system-ui,sans-serif; }',
        '#panel .empty { padding:10px 12px; color:#9aa3b0; }',
        '#trail { position:absolute; top:56px; right:12px; bottom:12px; width:min(340px,calc(100vw - 24px)); display:none; flex-direction:column; border:1px solid rgba(255,255,255,.14); border-radius:10px; background:rgba(21,23,28,.97); box-shadow:0 14px 44px rgba(0,0,0,.5); overflow:hidden; pointer-events:auto; }',
        '#trail.open { display:flex; }',
        '#taskPanel { position:absolute; top:56px; left:12px; bottom:12px; width:min(360px,calc(100vw - 24px)); display:none; flex-direction:column; border:1px solid rgba(255,255,255,.14); border-radius:10px; background:rgba(21,23,28,.97); box-shadow:0 14px 44px rgba(0,0,0,.5); overflow:hidden; pointer-events:auto; }',
        '#taskPanel.open { display:flex; }',
        '#taskPanel .task-head { display:flex; align-items:center; justify-content:space-between; padding:9px 12px; border-bottom:1px solid rgba(255,255,255,.1); font:600 13px system-ui,sans-serif; color:#edf0f4; flex:none; }',
        '#taskPanel .task-close { width:24px; height:24px; border:0; border-radius:6px; background:transparent; color:#aab2c0; cursor:pointer; font:15px/1 system-ui,sans-serif; }',
        '#taskPanel .task-close:hover { background:rgba(255,255,255,.13); color:#fff; }',
        '#taskList { flex:1; overflow-y:auto; padding:6px; }',
        '#taskPanel .task-row { box-sizing:border-box; width:100%; height:auto; min-height:64px; display:flex; flex-direction:column; align-items:stretch; gap:3px; padding:8px 10px; border:1px solid transparent; border-radius:6px; background:transparent; color:#dfe4ec; text-align:left; font:13px/1.35 system-ui,sans-serif; }',
        '#taskPanel .task-row:hover { background:rgba(255,255,255,.07); }',
        '#taskPanel .task-row:disabled { cursor:default; opacity:.48; }',
        '#taskPanel .task-row:disabled:hover { background:transparent; }',
        '#taskPanel .task-row.active { border-color:rgba(103,161,255,.5); background:rgba(103,161,255,.12); }',
        '#taskPanel .task-title { display:flex; align-items:center; gap:7px; color:#edf0f4; font-weight:600; }',
        '#taskPanel .task-state { width:7px; height:7px; flex:none; border-radius:50%; background:#77808d; }',
        '#taskPanel .task-row.active .task-state { background:#5fca7c; }',
        '#taskPanel .task-meta { color:#aab2c0; font-size:11px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
        '#taskPanel .task-latest { color:#8fb2ff; font-size:11px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
        '#trail .t-head { display:flex; align-items:center; justify-content:space-between; padding:9px 12px; border-bottom:1px solid rgba(255,255,255,.1); font:600 13px system-ui,sans-serif; color:#edf0f4; flex:none; }',
        '#trail .t-close { width:24px; height:24px; border:0; border-radius:6px; background:transparent; color:#aab2c0; cursor:pointer; font:15px/1 system-ui,sans-serif; }',
        '#trail .t-close:hover { background:rgba(255,255,255,.13); color:#fff; }',
        '#trail #trailList { flex:1; overflow-y:auto; padding:6px; }',
        '#trail .t-item { display:flex; flex-direction:column; gap:2px; padding:8px 10px; border-radius:6px; border-bottom:1px solid rgba(255,255,255,.05); }',
        '#trail .t-item:hover { background:rgba(255,255,255,.05); }',
        '#trail .t-time { color:#8fb2ff; font:11px/1.4 monospace; }',
        '#trail .t-text { color:#dfe4ec; word-break:break-all; font:13px/1.5 system-ui,sans-serif; }',
        '#trail .t-flag { font-size:11px; }',
        '#trail .t-flag.ok { color:#5fca7c; }',
        '#trail .t-flag.err { color:#ff8a8a; }',
        '</style>',
        '<div id="bar" role="toolbar" aria-label="DSH browser controls">',
        '<button id="back" type="button" aria-label="后退" title="后退"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></button>',
        '<button id="forward" type="button" aria-label="前进" title="前进"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18l6-6-6-6"/></svg></button>',
        '<button id="reload" type="button" aria-label="刷新" title="刷新"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-2.64-6.36"/><polyline points="21 3 21 9 15 9"/></svg></button>',
        '<button id="stop" type="button" aria-label="停止加载" title="停止加载"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="6" width="12" height="12" rx="2"/></svg></button>',
        '<button id="home" type="button" aria-label="主页" title="主页"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.75V21h14V9.75"/></svg></button>',
        '<button id="bookmarks" type="button" aria-label="收藏" title="收藏"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3.5l2.6 5.3 5.9.9-4.2 4.1 1 5.8-5.3-2.8-5.3 2.8 1-5.8-4.2-4.1 5.9-.9z"/></svg></button>',
        '<button id="trailBtn" type="button" aria-label="操作轨迹" title="操作轨迹"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></button>',
        '<button id="tasksBtn" type="button" aria-label="任务" title="任务"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="5" width="16" height="14" rx="2"/><path d="M8 9h8M8 13h5"/></svg></button>',
        '<input id="address" type="text" spellcheck="false" aria-label="地址栏" />',
        '</div>',
        '<div id="panel" role="menu" aria-label="收藏列表">',
        '<button id="saveBookmark" class="save" type="button">★ 收藏当前页</button>',
        '<div id="bookmarkList"></div>',
        '</div>',
        '<div id="trail" role="menu" aria-label="操作轨迹">',
        '<div class="t-head"><span>操作轨迹</span><button id="trailClose" class="t-close" type="button" aria-label="关闭轨迹">×</button></div>',
        '<div id="trailList"></div>',
        '</div>',
        '<div id="taskPanel" role="menu" aria-label="浏览器任务">',
        '<div class="task-head"><span>浏览器任务</span><button id="taskClose" class="task-close" type="button" aria-label="关闭任务">×</button></div>',
        '<div id="taskList"></div>',
        '</div>',
    ].join('\n');
    return [
        '(() => {',
        '  if (window.top !== window) return',
        '',
        '  const hostId = ' + JSON.stringify(PAGE_CHROME_HOST_ID),
        '  const chromeAttribute = ' + JSON.stringify(PAGE_CHROME_ATTRIBUTE),
        '  const normalizeAddress = (' + normalizer + ')',
        '',
        '  const mount = () => {',
        '    if (document.getElementById(hostId) || !document.documentElement) return',
        "    const host = document.createElement('div')",
        '    host.id = hostId',
        "    host.setAttribute(chromeAttribute, '')",
        "    host.style.cssText = 'all:initial;position:fixed;inset:0;z-index:2147483647;pointer-events:none'",
        "    const root = host.attachShadow({ mode: 'closed' })",
        '    root.innerHTML = ' + JSON.stringify(toolbarHtml),
        '    document.documentElement.append(host)',
        '',
        "    const back = root.getElementById('back')",
        "    const forward = root.getElementById('forward')",
        "    const reload = root.getElementById('reload')",
        "    const stop = root.getElementById('stop')",
        "    const home = root.getElementById('home')",
        "    const bookmarks = root.getElementById('bookmarks')",
        "    const trail = root.getElementById('trailBtn')",
        "    const trailPanel = root.getElementById('trail')",
        "    const tasksBtn = root.getElementById('tasksBtn')",
        "    const taskPanel = root.getElementById('taskPanel')",
        "    const taskList = root.getElementById('taskList')",
        "    const taskClose = root.getElementById('taskClose')",
        "    const trailList = root.getElementById('trailList')",
        "    const trailClose = root.getElementById('trailClose')",
        "    const address = root.getElementById('address')",
        "    const panel = root.getElementById('panel')",
        "    const saveBookmark = root.getElementById('saveBookmark')",
        "    const bookmarkList = root.getElementById('bookmarkList')",
        '    if (!(back instanceof HTMLButtonElement) || !(forward instanceof HTMLButtonElement) || !(reload instanceof HTMLButtonElement) || !(stop instanceof HTMLButtonElement) || !(home instanceof HTMLButtonElement) || !(bookmarks instanceof HTMLButtonElement) || !(address instanceof HTMLInputElement) || !(panel instanceof HTMLElement) || !(saveBookmark instanceof HTMLButtonElement) || !(bookmarkList instanceof HTMLElement) || !(trail instanceof HTMLButtonElement) || !(trailPanel instanceof HTMLElement) || !(trailList instanceof HTMLElement) || !(trailClose instanceof HTMLButtonElement) || !(tasksBtn instanceof HTMLButtonElement) || !(taskPanel instanceof HTMLElement) || !(taskList instanceof HTMLElement) || !(taskClose instanceof HTMLButtonElement)) return',
        '',
        "    const refreshAddress = () => { if (root.activeElement !== address) address.value = location.href }",
        "    const navigate = () => { const target = normalizeAddress(address.value); if (target !== '') location.assign(target) }",
        "    const bookmarksKey = 'dsh-chrome-bookmarks'",
        "    const loadBookmarks = () => { try { const v = JSON.parse(localStorage.getItem(bookmarksKey) || '[]'); return Array.isArray(v) ? v : [] } catch { return [] } }",
        '    const saveBookmarks = (list) => { try { localStorage.setItem(bookmarksKey, JSON.stringify(list)) } catch { /* quota */ } }',
        '    const renderBookmarks = () => {',
        '      const list = loadBookmarks()',
        "      bookmarkList.textContent = ''",
        "      if (list.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无收藏'; bookmarkList.append(empty); return }",
        '      for (const item of list) {',
        "        const row = document.createElement('div')",
        "        row.className = 'item'",
        "        const t = document.createElement('span'); t.className = 't'; t.textContent = item.title || item.url",
        "        const u = document.createElement('span'); u.className = 'u'; u.textContent = item.url",
        "        const x = document.createElement('button'); x.className = 'x'; x.type = 'button'; x.textContent = '×'; x.title = '删除收藏'",
        "        x.addEventListener('click', event => { event.stopPropagation(); saveBookmarks(loadBookmarks().filter(b => b.url !== item.url)); renderBookmarks(); updateBookmarkStar() })",
        "        row.addEventListener('click', () => { panel.classList.remove('open'); location.assign(item.url) })",
        '        row.append(t, u, x)',
        '        bookmarkList.append(row)',
        '      }',
        '    }',
        "    const starSvg = bookmarks.querySelector('svg')",
        "    const updateBookmarkStar = () => { if (starSvg) starSvg.setAttribute('fill', loadBookmarks().some(b => b.url === location.href) ? 'currentColor' : 'none') }",
        "    const spinReload = () => { reload.classList.add('spinning'); window.setTimeout(() => reload.classList.remove('spinning'), 500) }",
        "    const fmtTime = (at) => { const d = new Date(Number(at) || Date.now()); return String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0') + ':' + String(d.getSeconds()).padStart(2, '0') }",
        "    const fmtDate = (at) => { const d = new Date(Number(at) || Date.now()); return (d.getMonth() + 1) + '/' + d.getDate() }",
        "    const describe = (entry) => {",
        "      const p = entry.params || {}",
        "      switch (entry.action) {",
        "        case 'navigate': return '导航到 ' + String(p.url || '').slice(0, 80)",
        "        case 'click': return '点击 (' + p.x + ', ' + p.y + ')'",
        "        case 'fill': return '填写表单 ' + (Array.isArray(p.fields) ? p.fields.length : p.fields ?? 1) + ' 项'",
        "        case 'type': return '输入文字' + (p.text ? '（' + String(p.text).slice(0, 20) + '…）' : '')",
        "        case 'execute': return '执行页面脚本'",
        "        case 'screenshot': return '截图' + (p.fullPage ? '（整页）' : '')",
        "        case 'download': return '下载 ' + String(p.savePath || p.url || '').slice(0, 60)",
        "        case 'content': return '读取页面内容' + (p.selector ? '（' + p.selector + '）' : '')",
        "        case 'snapshot': return '页面快照'",
        "        default: return String(entry.action || '')",
        "      }",
        "    }",
        "    const renderTrail = () => {",
        "      const list = Array.isArray(window.__dshTrail) ? window.__dshTrail : []",
        "      trailList.textContent = ''",
        "      if (list.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无操作记录'; trailList.append(empty); return }",
        "      const items = [...list].reverse()",
        "      let lastDay = ''",
        "      for (const entry of items) {",
        "        const day = fmtDate(entry.at)",
        "        if (day !== lastDay) {",
        "          const head = document.createElement('div'); head.className = 't-time'; head.textContent = '— ' + day + ' —'; head.style.cssText = 'text-align:center;margin:6px 0 4px;color:#8fb2ff'; trailList.append(head); lastDay = day",
        "        }",
        "        const row = document.createElement('div')",
        "        row.className = 't-item'",
        "        const top = document.createElement('div'); top.style.cssText = 'display:flex;align-items:center;gap:6px'",
        "        const time = document.createElement('span'); time.className = 't-time'; time.textContent = fmtTime(entry.at)",
        "        const flag = document.createElement('span'); flag.className = 't-flag ' + (entry.ok === false ? 'err' : 'ok'); flag.textContent = entry.ok === false ? '✗' : '✓'",
        "        top.append(time, flag)",
        "        const text = document.createElement('span'); text.className = 't-text'; text.textContent = describe(entry)",
        "        row.append(top, text)",
        "        trailList.append(row)",
        "      }",
        "    }",
        "    window.__dshTrailRender = renderTrail",
        "    const emitTaskAction = taskKey => { try { const binding = window.__dshBrowserTaskAction; if (typeof binding === 'function') binding(JSON.stringify({ type: 'switch-task', taskKey })) } catch { /* host unavailable */ } }",
        "    const latestText = latest => { if (!latest || typeof latest !== 'object') return ''; const action = String(latest.action || ''); return action === '' ? '' : action + (latest.at ? ' · ' + fmtTime(latest.at) : '') }",
        "    const renderTasks = () => {",
        "      const tasks = Array.isArray(window.__dshTasks) ? window.__dshTasks : []",
        "      taskList.textContent = ''",
        "      if (tasks.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无浏览器任务'; taskList.append(empty); return }",
        "      for (const task of tasks) {",
        "        if (!task || typeof task !== 'object') continue",
        "        const taskKey = typeof task.key === 'string' && task.key.trim() !== '' ? task.key : undefined",
        "        const row = document.createElement('button'); row.type = 'button'; row.className = 'task-row' + (task.active ? ' active' : ''); row.disabled = taskKey === undefined",
        "        const thumb = document.createElement('div'); thumb.className = 'task-thumb'; const source = typeof task.thumbnail === 'string' ? task.thumbnail : ''; if (source.startsWith('data:image/')) { const image = document.createElement('img'); image.alt = ''; image.src = source; thumb.append(image) } else { const origin = typeof task.url === 'string' ? task.url.replace(/^https?:\\/\\//, '') : ''; thumb.textContent = (origin === '' ? 'DSH' : origin.toUpperCase().slice(0, 2)) }",
        "        const title = document.createElement('span'); title.className = 'task-title'",
        "        const state = document.createElement('span'); state.className = 'task-state'; state.setAttribute('aria-label', task.active ? '当前任务' : '后台任务')",
        "        const label = document.createElement('span'); label.textContent = (typeof task.label === 'string' && task.label !== '' ? task.label : (taskKey === undefined ? '未命名任务' : taskKey.slice(0, 12)))",
        "        title.append(state, label)",
        "        const meta = document.createElement('span'); meta.className = 'task-meta'; meta.textContent = (task.active ? '当前' : '后台') + ' · ' + (Number.isFinite(task.tabs) ? task.tabs : 0) + ' 个标签页' + (typeof task.url === 'string' && task.url !== '' ? ' · ' + task.url : '')",
        "        row.append(thumb, title, meta)",
        "        const latest = latestText(task.latest); if (latest !== '') { const recent = document.createElement('span'); recent.className = 'task-latest'; recent.textContent = latest; row.append(recent) }",
        "        if (taskKey !== undefined) row.addEventListener('click', () => emitTaskAction(taskKey))",
        "        taskList.append(row)",
        "      }",
        "    }",
        "    window.__dshTaskRender = renderTasks",
        "    const toggleTrail = () => { const open = trailPanel.classList.toggle('open'); if (open) { panel.classList.remove('open'); renderTrail() } }",
        "    const closeTrail = () => trailPanel.classList.remove('open')",
        "    const toggleTasks = () => { const open = taskPanel.classList.toggle('open'); if (open) { panel.classList.remove('open'); renderTasks() } }",
        "    const closeTasks = () => taskPanel.classList.remove('open')",
        "    const togglePanel = () => { const open = panel.classList.toggle('open'); if (open) { trailPanel.classList.remove('open'); taskPanel.classList.remove('open'); renderBookmarks(); updateBookmarkStar() } }",
        '',
        "    back.addEventListener('click', () => history.back())",
        "    forward.addEventListener('click', () => history.forward())",
        "    reload.addEventListener('click', () => { spinReload(); location.reload() })",
        "    stop.addEventListener('click', () => window.stop())",
        "    home.addEventListener('click', () => location.assign('https://www.bing.com'))",
        "    bookmarks.addEventListener('click', togglePanel)",
        "    trail.addEventListener('click', toggleTrail)",
        "    trailClose.addEventListener('click', closeTrail)",
        "    tasksBtn.addEventListener('click', toggleTasks)",
        "    taskClose.addEventListener('click', closeTasks)",
        "    saveBookmark.addEventListener('click', () => {",
        '      const list = loadBookmarks().filter(b => b.url !== location.href)',
        "      list.unshift({ url: location.href, title: document.title || location.href })",
        '      saveBookmarks(list)',
        '      renderBookmarks()',
        '      updateBookmarkStar()',
        '    })',
        "    address.addEventListener('keydown', event => {",
        "      if (event.key === 'Enter') { event.preventDefault(); navigate() }",
        "      else if (event.key === 'Escape') address.blur()",
        '    })',
        "    window.addEventListener('keydown', event => {",
        "      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'l') { event.preventDefault(); address.focus(); address.select() }",
        '    }, true)',
        "    window.addEventListener('popstate', refreshAddress)",
        "    window.addEventListener('hashchange', refreshAddress)",
        '',
        "    // User-control signal: mark the host so model-facing snapshots can tell",
        "    // that a human is driving this page right now (ego's handoff semantics).",
        '    let lastUserActivity = 0',
        "    const markUserActive = () => { lastUserActivity = Date.now(); host.setAttribute('data-dsh-user-active', '1') }",
        "    window.addEventListener('pointerdown', markUserActive, true)",
        "    window.addEventListener('keydown', markUserActive, true)",
        "    window.setInterval(() => { if (lastUserActivity !== 0 && Date.now() - lastUserActivity > 60000) host.removeAttribute('data-dsh-user-active') }, 15000)",
        '',
        '    refreshAddress()',
        '    window.setInterval(refreshAddress, 750)',
        '  }',
        '',
        "  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount, { once: true })",
        '  else mount()',
        '})()',
    ].join('\n');
}
