/**
 * Human-facing browser chrome injected into the top-level page document.
 * Keeping this UI in the page renderer avoids a second Electron
 * WebContentsView and leaves the host composition tree stable.
 */
export const PAGE_CHROME_HOST_ID = '__dsh_browser_chrome_host__'
export const PAGE_CHROME_ATTRIBUTE = 'data-dsh-browser-chrome'

/** Generated once; stable across documents and reused by the provider. */
export const PAGE_CHROME_SCRIPT = buildPageChromeScript()

/** Convert human address-bar text into an allowed HTTP(S) navigation target. */
export function normalizeBrowserAddress(raw: string): string {
  const value = raw.trim()
  if (value === '') return ''
  if (/^https?:\/\//i.test(value)) return value
  if (/^[a-z][a-z0-9+.-]*:/i.test(value)) return ''
  if (value.includes(' ') || !value.includes('.')) {
    return 'https://www.bing.com/search?q=' + encodeURIComponent(value)
  }
  return 'https://' + value
}

/** Build a self-contained CDP page-start script. */
export function buildPageChromeScript(): string {
  const normalizer = normalizeBrowserAddress.toString()
  const toolbarHtml = [
    '<style>',
    '#bar { position:absolute; top:8px; left:50%; transform:translateX(-50%); box-sizing:border-box; width:min(940px,calc(100vw - 24px)); min-height:42px; display:flex; align-items:center; gap:6px; padding:6px 8px; border:1px solid rgba(255,255,255,.20); border-radius:18px; background:rgba(20,28,40,.56); backdrop-filter:blur(24px) saturate(145%); box-shadow:0 18px 42px rgba(8,15,29,.30),0 4px 12px rgba(65,116,181,.18),inset 0 1px 0 rgba(255,255,255,.12); color:#f0f5ff; font:13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; pointer-events:auto; }',
    'button { width:30px; height:28px; border:0; border-radius:8px; background:transparent; color:inherit; cursor:pointer; font:18px/1 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; transition:background .18s ease,transform .18s ease; }',
    'button:hover { background:rgba(255,255,255,.13); }',
    'button:active { transform:scale(.94); }',
    'button:focus-visible { outline:2px solid rgba(132,181,255,.88); outline-offset:2px; }',
    '#bar button svg { display:block; margin:auto; }',
    '#bar button.spinning { animation:dshSpin .5s linear; }',
    '@keyframes dshSpin { to { transform:rotate(360deg); } }',
    '#address { box-sizing:border-box; flex:1; min-width:80px; height:28px; padding:0 11px; border:1px solid rgba(255,255,255,.16); border-radius:14px; outline:none; background:rgba(5,12,24,.24); color:inherit; font:inherit; }',
    '#address:focus { border-color:#83b7ff; box-shadow:0 0 0 2px rgba(131,183,255,.24); }',
    '#panel { position:absolute; top:56px; left:50%; transform:translateX(-50%); box-sizing:border-box; width:min(420px,calc(100vw - 24px)); max-height:320px; overflow:auto; display:none; border:1px solid rgba(255,255,255,.20); border-radius:16px; background:rgba(19,27,39,.76); backdrop-filter:blur(24px) saturate(145%); box-shadow:0 18px 42px rgba(8,15,29,.34),inset 0 1px 0 rgba(255,255,255,.12); padding:8px; color:#f0f5ff; font:13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; pointer-events:auto; }',
    '#panel.open { display:block; }',
    '#panel .save { width:auto; padding:0 12px; height:30px; border:1px solid rgba(160,200,255,.28); border-radius:8px; background:rgba(99,157,236,.16); color:#dceaff; font:13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; cursor:pointer; }',
    '#panel .item { display:flex; align-items:center; gap:8px; padding:7px 9px; border-radius:8px; cursor:pointer; }',
    '#panel .item:hover { background:rgba(255,255,255,.09); }',
    '#panel .item .t { flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
    '#panel .item .u { color:#a8c9ff; font-size:11px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; max-width:180px; }',
    '#panel .item .x { width:24px; height:24px; font:14px/1 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '.empty { padding:12px; color:#aeb9ca; font:13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '.glass-panel { position:absolute; top:68px; bottom:12px; display:none; flex-direction:column; border:1px solid rgba(255,255,255,.20); border-radius:20px; background:rgba(19,27,39,.62); backdrop-filter:blur(30px) saturate(155%); box-shadow:0 22px 54px rgba(7,14,28,.35),0 5px 16px rgba(70,122,190,.16),inset 0 1px 0 rgba(255,255,255,.12); overflow:hidden; color:#eef4ff; font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; pointer-events:auto; }',
    '#trail { right:12px; width:344px; }',
    '#trail.open, #taskPanel.open { display:flex; }',
    '#taskPanel { left:12px; width:368px; }',
    '#taskPanel .task-head, #trail .t-head { display:flex; align-items:center; justify-content:space-between; padding:11px 13px; border-bottom:1px solid rgba(255,255,255,.12); color:#f2f6ff; font:600 13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; flex:none; }',
    '#taskPanel .task-close, #trail .t-close { width:24px; height:24px; border:0; border-radius:7px; background:transparent; color:#b7c4d5; cursor:pointer; font:15px/1 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '#taskPanel .task-close:hover, #trail .t-close:hover { background:rgba(255,255,255,.13); color:#fff; }',
    '#taskList { flex:1; overflow-y:auto; padding:8px; }',
    '#taskPanel .task-row { box-sizing:border-box; width:100%; min-height:80px; display:grid; grid-template-columns:94px minmax(0,1fr); grid-template-rows:auto auto auto; column-gap:10px; row-gap:3px; align-items:center; padding:8px; border:1px solid transparent; border-radius:14px; background:transparent; color:#e5edf9; text-align:left; font:13px/1.35 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '#taskPanel .task-row:hover { background:rgba(255,255,255,.07); }',
    '#taskPanel .task-row:disabled { cursor:default; opacity:.48; }',
    '#taskPanel .task-row:disabled:hover { background:transparent; }',
    '#taskPanel .task-row.active { border-color:rgba(124,178,255,.62); background:rgba(85,143,224,.13); box-shadow:inset 0 1px 0 rgba(255,255,255,.06); }',
    '#taskPanel .task-thumb { grid-row:1 / 4; width:94px; height:64px; display:grid; place-items:center; overflow:hidden; border-radius:14px; background:rgba(90,116,151,.30); color:#c9dcf8; font:600 11px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; letter-spacing:.04em; }',
    '#taskPanel .task-thumb canvas.task-thumb-canvas { display:block; width:100%; height:100%; }',
    '#taskPanel .task-title { display:flex; align-items:center; gap:7px; min-width:0; color:#f3f7ff; font-weight:600; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
    '#taskPanel .task-state { width:7px; height:7px; flex:none; border-radius:50%; background:#8792a1; }',
    '#taskPanel .task-row.active .task-state { background:#77d59a; }',
    '#taskPanel .task-meta, #taskPanel .task-latest { min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:11px; }',
    '#taskPanel .task-meta { color:#b8c5d6; }',
    '#taskPanel .task-latest { color:#acd0ff; }',
    '#trail #trailList { flex:1; overflow-y:auto; padding:8px 12px; }',
    '#trail .activity-day { color:#accbff; font:11px/1.4 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; text-align:center; margin:6px 0 5px; }',
    '#trail .activity-item { position:relative; display:grid; grid-template-columns:54px 16px minmax(0,1fr); column-gap:7px; align-items:start; padding:8px 0; }',
    '#trail .activity-item:hover { background:rgba(255,255,255,.045); }',
    '#trail .timeline-rail { position:relative; width:16px; min-height:30px; }',
    '#trail .timeline-rail::before { content:""; position:absolute; top:4px; bottom:-14px; left:7px; width:1px; background:rgba(181,208,245,.28); }',
    '#trail .activity-item:last-child .timeline-rail::before { display:none; }',
    '#trail .t-time { color:#a8caff; font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace; font-variant-numeric:tabular-nums; }',
    '#trail .t-flag { position:relative; z-index:1; display:grid; place-items:center; width:14px; height:14px; border-radius:50%; background:rgba(78,111,154,.72); color:#f2f7ff; font-size:9px; line-height:1; }',
    '#trail .t-flag.ok { color:#a6efbc; }',
    '#trail .t-flag.err { color:#ffb3b3; }',
    '#trail .t-text { color:#e3ebf8; word-break:break-word; font:12px/1.45 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '@media (max-width:760px) { #bar { width:calc(100vw - 16px); } #taskPanel { left:8px; right:8px; top:64px; bottom:auto; height:min(42vh,320px); width:auto; } #trail { left:8px; right:8px; top:auto; bottom:8px; height:min(42vh,320px); width:auto; } }',
    '</style>',
    '<div id="bar" role="toolbar" aria-label="DSH browser controls">',
    '<button id="back" type="button" aria-label="后退" title="后退"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></button>',
    '<button id="forward" type="button" aria-label="前进" title="前进"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18l6-6-6-6"/></svg></button>',
    '<button id="reload" type="button" aria-label="刷新" title="刷新"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-2.64-6.36"/><polyline points="21 3 21 9 15 9"/></svg></button>',
    '<button id="stop" type="button" aria-label="停止加载" title="停止加载"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="6" width="12" height="12" rx="2"/></svg></button>',
    '<button id="home" type="button" aria-label="主页" title="主页"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.75V21h14V9.75"/></svg></button>',
    '<button id="bookmarks" type="button" aria-label="收藏" title="收藏"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3.5l2.6 5.3 5.9.9-4.2 4.1 1 5.8-5.3-2.8-5.3 2.8 1-5.8-4.2-4.1 5.9-.9z"/></svg></button>',
    '<button id="trailBtn" type="button" aria-label="操作轨迹" title="操作轨迹"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></button>',
    '<button id="tasksBtn" type="button" aria-label="任务" title="任务"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="5" width="16" height="14" rx="2"/><path d="M8 9h8M8 13h5"/></svg></button>',
    '<input id="address" type="text" spellcheck="false" aria-label="地址栏" />',
    '</div>',
    '<div id="panel" role="menu" aria-label="收藏列表">',
    '<button id="saveBookmark" class="save" type="button">★ 收藏当前页</button>',
    '<div id="bookmarkList"></div>',
    '</div>',
    '<div id="trail" class="glass-panel" role="menu" aria-label="操作轨迹">',
    '<div class="t-head"><span>操作轨迹</span><button id="trailClose" class="t-close" type="button" aria-label="关闭轨迹">×</button></div>',
    '<div id="trailList"></div>',
    '</div>',
    '<div id="taskPanel" class="glass-panel" role="menu" aria-label="浏览器任务">',
    '<div class="task-head"><span>浏览器任务</span><button id="taskClose" class="task-close" type="button" aria-label="关闭任务">×</button></div>',
    '<div id="taskList"></div>',
    '</div>',
  ].join('\n')

  return [
    '(() => {',
    '  if (window.top !== window) return',
    '',
    '  const hostId = ' + JSON.stringify(PAGE_CHROME_HOST_ID),
    '  const chromeAttribute = ' + JSON.stringify(PAGE_CHROME_ATTRIBUTE),
    '  const normalizeAddress = (' + normalizer + ')',
    '',
    '  const mount = () => {',
    '    if (document.getElementById(hostId) || !document.documentElement) return',
    "    const host = document.createElement('div')",
    '    host.id = hostId',
    "    host.setAttribute(chromeAttribute, '')",
    "    host.style.cssText = 'all:initial;position:fixed;inset:0;z-index:2147483647;pointer-events:none'",
    "    const root = host.attachShadow({ mode: 'closed' })",
    '    root.innerHTML = ' + JSON.stringify(toolbarHtml),
    '    document.documentElement.append(host)',
    '',
    "    const back = root.getElementById('back')",
    "    const forward = root.getElementById('forward')",
    "    const reload = root.getElementById('reload')",
    "    const stop = root.getElementById('stop')",
    "    const home = root.getElementById('home')",
    "    const bookmarks = root.getElementById('bookmarks')",
    "    const trail = root.getElementById('trailBtn')",
    "    const trailPanel = root.getElementById('trail')",
    "    const tasksBtn = root.getElementById('tasksBtn')",
    "    const taskPanel = root.getElementById('taskPanel')",
    "    const taskList = root.getElementById('taskList')",
    "    const taskClose = root.getElementById('taskClose')",
    "    const trailList = root.getElementById('trailList')",
    "    const trailClose = root.getElementById('trailClose')",
    "    const address = root.getElementById('address')",
    "    const panel = root.getElementById('panel')",
    "    const saveBookmark = root.getElementById('saveBookmark')",
    "    const bookmarkList = root.getElementById('bookmarkList')",
    '    if (!(back instanceof HTMLButtonElement) || !(forward instanceof HTMLButtonElement) || !(reload instanceof HTMLButtonElement) || !(stop instanceof HTMLButtonElement) || !(home instanceof HTMLButtonElement) || !(bookmarks instanceof HTMLButtonElement) || !(address instanceof HTMLInputElement) || !(panel instanceof HTMLElement) || !(saveBookmark instanceof HTMLButtonElement) || !(bookmarkList instanceof HTMLElement) || !(trail instanceof HTMLButtonElement) || !(trailPanel instanceof HTMLElement) || !(trailList instanceof HTMLElement) || !(trailClose instanceof HTMLButtonElement) || !(tasksBtn instanceof HTMLButtonElement) || !(taskPanel instanceof HTMLElement) || !(taskList instanceof HTMLElement) || !(taskClose instanceof HTMLButtonElement)) return',
    '',
    "    const refreshAddress = () => { if (root.activeElement !== address) address.value = location.href }",
    "    const navigate = () => { const target = normalizeAddress(address.value); if (target !== '') location.assign(target) }",
    "    const bookmarksKey = 'dsh-chrome-bookmarks'",
    "    const loadBookmarks = () => { try { const v = JSON.parse(localStorage.getItem(bookmarksKey) || '[]'); return Array.isArray(v) ? v : [] } catch { return [] } }",
    '    const saveBookmarks = (list) => { try { localStorage.setItem(bookmarksKey, JSON.stringify(list)) } catch { /* quota */ } }',
    '    const renderBookmarks = () => {',
    '      const list = loadBookmarks()',
    "      bookmarkList.textContent = ''",
    "      if (list.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无收藏'; bookmarkList.append(empty); return }",
    '      for (const item of list) {',
    "        const row = document.createElement('div')",
    "        row.className = 'item'",
    "        const t = document.createElement('span'); t.className = 't'; t.textContent = item.title || item.url",
    "        const u = document.createElement('span'); u.className = 'u'; u.textContent = item.url",
    "        const x = document.createElement('button'); x.className = 'x'; x.type = 'button'; x.textContent = '×'; x.title = '删除收藏'",
    "        x.addEventListener('click', event => { event.stopPropagation(); saveBookmarks(loadBookmarks().filter(b => b.url !== item.url)); renderBookmarks(); updateBookmarkStar() })",
    "        row.addEventListener('click', () => { panel.classList.remove('open'); location.assign(item.url) })",
    '        row.append(t, u, x)',
    '        bookmarkList.append(row)',
    '      }',
    '    }',
    "    const starSvg = bookmarks.querySelector('svg')",
    "    const updateBookmarkStar = () => { if (starSvg) starSvg.setAttribute('fill', loadBookmarks().some(b => b.url === location.href) ? 'currentColor' : 'none') }",
    "    const spinReload = () => { reload.classList.add('spinning'); window.setTimeout(() => reload.classList.remove('spinning'), 500) }",
    "    const fmtTime = (at) => { const d = new Date(Number(at) || Date.now()); return String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0') + ':' + String(d.getSeconds()).padStart(2, '0') }",
    "    const fmtDate = (at) => { const d = new Date(Number(at) || Date.now()); return (d.getMonth() + 1) + '/' + d.getDate() }",
    "    const describe = (entry) => {",
    "      const p = entry.params || {}",
    "      switch (entry.action) {",
    "        case 'navigate': return '导航到 ' + String(p.url || '').slice(0, 80)",
    "        case 'click': return '点击 (' + p.x + ', ' + p.y + ')'",
    "        case 'fill': return '填写表单 ' + (Array.isArray(p.fields) ? p.fields.length : p.fields ?? 1) + ' 项'",
    "        case 'type': return '输入文字' + (p.text ? '（' + String(p.text).slice(0, 20) + '…）' : '')",
    "        case 'execute': return '执行页面脚本'",
    "        case 'screenshot': return '截图' + (p.fullPage ? '（整页）' : '')",
    "        case 'download': return '下载 ' + String(p.savePath || p.url || '').slice(0, 60)",
    "        case 'content': return '读取页面内容' + (p.selector ? '（' + p.selector + '）' : '')",
    "        case 'snapshot': return '页面快照'",
    "        default: return String(entry.action || '')",
    "      }",
    "    }",
    "    const renderTrail = () => {",
    "      const list = Array.isArray(window.__dshTrail) ? window.__dshTrail : []",
    "      trailList.textContent = ''",
    "      if (list.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无操作记录'; trailList.append(empty); return }",
    "      const items = [...list].reverse()",
    "      let lastDay = ''",
    "      for (const entry of items) {",
    "        const day = fmtDate(entry.at)",
    "        if (day !== lastDay) {",
    "          const head = document.createElement('div'); head.className = 'activity-day'; head.textContent = '— ' + day + ' —'; trailList.append(head); lastDay = day",
    "        }",
    "        const row = document.createElement('div')",
    "        row.className = 'activity-item'",
    "        const time = document.createElement('span'); time.className = 't-time'; time.textContent = fmtTime(entry.at)",
    "        const rail = document.createElement('div'); rail.className = 'timeline-rail'",
    "        const flag = document.createElement('span'); flag.className = 't-flag ' + (entry.ok === false ? 'err' : 'ok'); flag.textContent = entry.ok === false ? '✗' : '✓'",
    "        rail.append(flag)",
    "        const text = document.createElement('span'); text.className = 't-text'; text.textContent = describe(entry)",
    "        row.append(time, rail, text)",
    "        trailList.append(row)",
    "      }",
    "    }",
    "    window.__dshTrailRender = renderTrail",
    "    const emitTaskAction = taskKey => { try { const binding = window.__dshBrowserTaskAction; if (typeof binding === 'function') binding(JSON.stringify({ type: 'switch-task', taskKey })) } catch { /* host unavailable */ } }",
    "    const emitWorkspacePanels = (tasks, trail) => { try { const binding = window.__dshBrowserTaskAction; if (typeof binding === 'function') binding(JSON.stringify({ type: 'set-workspace-panels', tasks, trail })) } catch { /* host unavailable */ } }",
    "    const latestText = latest => { if (!latest || typeof latest !== 'object') return ''; const action = String(latest.action || ''); return action === '' ? '' : action + (latest.at ? ' · ' + fmtTime(latest.at) : '') }",
    "    const renderTasks = () => {",
    "      const tasks = Array.isArray(window.__dshTasks) ? window.__dshTasks : []",
    "      taskList.textContent = ''",
    "      if (tasks.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无浏览器任务'; taskList.append(empty); return }",
    "      for (const task of tasks) {",
    "        if (!task || typeof task !== 'object') continue",
    "        const taskKey = typeof task.key === 'string' && task.key.trim() !== '' ? task.key : undefined",
    "        const row = document.createElement('button'); row.type = 'button'; row.className = 'task-row' + (task.active ? ' active' : ''); row.disabled = taskKey === undefined",
    "        const thumb = document.createElement('div'); thumb.className = 'task-thumb'; const source = typeof task.thumbnail === 'string' ? task.thumbnail : ''",
    "        const origin = typeof task.url === 'string' ? task.url.replace(/^https?:\\/\\//, '') : ''",
    "        thumb.textContent = origin === '' ? 'DSH' : origin.toUpperCase().slice(0, 2)",
    "        if (source.startsWith('data:image/jpeg;base64,') && typeof createImageBitmap === 'function') {",
    "          try {",
    "            const payload = source.slice('data:image/jpeg;base64,'.length)",
    "            const bytes = Uint8Array.from(atob(payload), ch => ch.charCodeAt(0))",
    "            const blob = new Blob([bytes], { type: 'image/jpeg' })",
    "            createImageBitmap(blob).then(bitmap => {",
    "              const canvas = document.createElement('canvas')",
    "              canvas.className = 'task-thumb-canvas'",
    "              canvas.width = 188",
    "              canvas.height = 128",
    "              const ctx = canvas.getContext('2d')",
    "              if (!ctx) {",
    "                if (typeof bitmap.close === 'function') bitmap.close()",
    "                return",
    "              }",
    "              const scale = Math.max(canvas.width / bitmap.width, canvas.height / bitmap.height)",
    "              const drawnWidth = bitmap.width * scale",
    "              const drawnHeight = bitmap.height * scale",
    "              ctx.drawImage(bitmap, (canvas.width - drawnWidth) / 2, (canvas.height - drawnHeight) / 2, drawnWidth, drawnHeight)",
    "              if (typeof bitmap.close === 'function') bitmap.close()",
    "              if (thumb.isConnected) { thumb.textContent = ''; thumb.append(canvas) }",
    "            }).catch(() => { /* async decode failure keeps the origin/DSH fallback */ })",
    "          } catch { /* malformed payload keeps the origin/DSH fallback */ }",
    "        }",
    "        const title = document.createElement('span'); title.className = 'task-title'",
    "        const state = document.createElement('span'); state.className = 'task-state'; state.setAttribute('aria-label', task.active ? '当前任务' : '后台任务')",
    "        const label = document.createElement('span'); label.textContent = (typeof task.label === 'string' && task.label !== '' ? task.label : (taskKey === undefined ? '未命名任务' : taskKey.slice(0, 12)))",
    "        title.append(state, label)",
    "        const meta = document.createElement('span'); meta.className = 'task-meta'; meta.textContent = (task.active ? '当前' : '后台') + ' · ' + (Number.isFinite(task.tabs) ? task.tabs : 0) + ' 个标签页' + (typeof task.url === 'string' && task.url !== '' ? ' · ' + task.url : '')",
    "        row.append(thumb, title, meta)",
    "        const latest = latestText(task.latest); if (latest !== '') { const recent = document.createElement('span'); recent.className = 'task-latest'; recent.textContent = latest; row.append(recent) }",
    "        if (taskKey !== undefined) row.addEventListener('click', () => emitTaskAction(taskKey))",
    "        taskList.append(row)",
    "      }",
    "    }",
    "    window.__dshTaskRender = renderTasks",
    "    const applyWorkspacePanels = () => {",
    "      const state = window.__dshWorkspacePanels && typeof window.__dshWorkspacePanels === 'object' ? window.__dshWorkspacePanels : {}",
    "      const tasksOpen = state.tasks === true",
    "      const trailOpen = state.trail === true",
    "      taskPanel.classList.toggle('open', tasksOpen)",
    "      trailPanel.classList.toggle('open', trailOpen)",
    "    }",
    "    const syncWorkspacePanels = () => { const tasksOpen = taskPanel.classList.contains('open'); const trailOpen = trailPanel.classList.contains('open'); emitWorkspacePanels(tasksOpen, trailOpen) }",
    "    window.__dshWorkspaceRender = applyWorkspacePanels",
    "    const toggleTrail = () => { const open = trailPanel.classList.toggle('open'); if (open) { panel.classList.remove('open'); renderTrail() } syncWorkspacePanels() }",
    "    const closeTrail = () => { trailPanel.classList.remove('open'); syncWorkspacePanels() }",
    "    const toggleTasks = () => { const open = taskPanel.classList.toggle('open'); if (open) { panel.classList.remove('open'); renderTasks() } syncWorkspacePanels() }",
    "    const closeTasks = () => { taskPanel.classList.remove('open'); syncWorkspacePanels() }",
    "    const togglePanel = () => { const open = panel.classList.toggle('open'); if (open) { trailPanel.classList.remove('open'); taskPanel.classList.remove('open'); renderBookmarks(); updateBookmarkStar(); syncWorkspacePanels() } }",
    "    applyWorkspacePanels()",
    '',
    "    back.addEventListener('click', () => history.back())",
    "    forward.addEventListener('click', () => history.forward())",
    "    reload.addEventListener('click', () => { spinReload(); location.reload() })",
    "    stop.addEventListener('click', () => window.stop())",
    "    home.addEventListener('click', () => location.assign('https://www.bing.com'))",
    "    bookmarks.addEventListener('click', togglePanel)",
    "    trail.addEventListener('click', toggleTrail)",
    "    trailClose.addEventListener('click', closeTrail)",
    "    tasksBtn.addEventListener('click', toggleTasks)",
    "    taskClose.addEventListener('click', closeTasks)",
    "    saveBookmark.addEventListener('click', () => {",
    '      const list = loadBookmarks().filter(b => b.url !== location.href)',
    "      list.unshift({ url: location.href, title: document.title || location.href })",
    '      saveBookmarks(list)',
    '      renderBookmarks()',
    '      updateBookmarkStar()',
    '    })',
    "    address.addEventListener('keydown', event => {",
    "      if (event.key === 'Enter') { event.preventDefault(); navigate() }",
    "      else if (event.key === 'Escape') address.blur()",
    '    })',
    "    window.addEventListener('keydown', event => {",
    "      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'l') { event.preventDefault(); address.focus(); address.select() }",
    '    }, true)',
    "    window.addEventListener('popstate', refreshAddress)",
    "    window.addEventListener('hashchange', refreshAddress)",
    '',
    "    // User-control signal: mark the host so model-facing snapshots can tell",
    "    // that a human is driving this page right now (ego's handoff semantics).",
    '    let lastUserActivity = 0',
    "    const markUserActive = () => { lastUserActivity = Date.now(); host.setAttribute('data-dsh-user-active', '1') }",
    "    window.addEventListener('pointerdown', markUserActive, true)",
    "    window.addEventListener('keydown', markUserActive, true)",
    "    window.setInterval(() => { if (lastUserActivity !== 0 && Date.now() - lastUserActivity > 60000) host.removeAttribute('data-dsh-user-active') }, 15000)",
    '',
    '    refreshAddress()',
    '    window.setInterval(refreshAddress, 750)',
    '  }',
    '',
    "  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount, { once: true })",
    '  else mount()',
    '})()',
  ].join('\n')
}
