/**
 * Human-facing browser chrome injected into the top-level page document.
 * Keeping this UI in the page renderer avoids a second Electron
 * WebContentsView and leaves the host composition tree stable.
 */
export const PAGE_CHROME_HOST_ID = '__dsh_browser_chrome_host__'
export const PAGE_CHROME_ATTRIBUTE = 'data-dsh-browser-chrome'

/** Generated once; stable across documents and reused by the provider. */
export const PAGE_CHROME_SCRIPT = buildPageChromeScript()

/** Convert human address-bar text into an allowed HTTP(S) navigation target. */
export function normalizeBrowserAddress(raw: string): string {
  const value = raw.trim()
  if (value === '') return ''
  if (/^https?:\/\//i.test(value)) return value
  if (/^[a-z][a-z0-9+.-]*:/i.test(value)) return ''
  if (value.includes(' ') || !value.includes('.')) {
    return 'https://www.bing.com/search?q=' + encodeURIComponent(value)
  }
  return 'https://' + value
}

/** Build a self-contained CDP page-start script. */
export function buildPageChromeScript(): string {
  const normalizer = normalizeBrowserAddress.toString()
  const toolbarHtml = [
    '<style>',
    '#toolbarRevealZone { position:absolute; top:0; left:50%; transform:translateX(-50%); width:280px; height:56px; pointer-events:auto; }',
    '#toolbarReveal { position:absolute; top:-30px; left:50%; transform:translateX(-50%) scale(.84); box-sizing:border-box; width:28px; height:28px; padding:0; border:1px solid rgba(159,199,255,.34); border-radius:50%; background:rgba(24,43,69,.78); backdrop-filter:blur(16px) saturate(140%); box-shadow:0 8px 18px rgba(5,13,28,.24),inset 0 1px 0 rgba(255,255,255,.12); color:#e6f0ff; opacity:0; pointer-events:none; transition:top .20s ease,opacity .16s ease,transform .20s ease,background .16s ease; }',
    '#toolbarRevealZone.armed #toolbarReveal, #toolbarRevealZone:hover #toolbarReveal, #toolbarReveal:focus-visible { top:5px; transform:translateX(-50%) scale(1); opacity:1; pointer-events:auto; }',
    '#toolbarReveal:hover { background:rgba(48,82,129,.90); }',
    '#bar { position:absolute; top:0; left:50%; transform:translateX(-50%) translateY(calc(-100% - 8px)); box-sizing:border-box; width:min(940px,calc(100vw - 24px)); min-height:42px; display:flex; align-items:center; gap:6px; padding:6px 8px; border:1px solid rgba(255,255,255,.20); border-radius:0 0 18px 18px; background:rgba(20,28,40,.56); backdrop-filter:blur(24px) saturate(145%); box-shadow:0 18px 42px rgba(8,15,29,.30),0 4px 12px rgba(65,116,181,.18),inset 0 1px 0 rgba(255,255,255,.12); color:#f0f5ff; font:13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; opacity:0; pointer-events:none; transition:transform .24s cubic-bezier(.2,.8,.2,1),opacity .16s ease; }',
    '#bar.open { transform:translateX(-50%) translateY(8px); opacity:1; pointer-events:auto; }',
    'button { width:30px; height:28px; border:0; border-radius:8px; background:transparent; color:inherit; cursor:pointer; font:18px/1 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; transition:background .18s ease,transform .18s ease; }',
    'button:hover { background:rgba(255,255,255,.13); }',
    'button:active { transform:scale(.94); }',
    'button:focus-visible { outline:2px solid rgba(132,181,255,.88); outline-offset:2px; }',
    '#bar button svg { display:block; margin:auto; }',
    '#bar button.spinning { animation:dshSpin .5s linear; }',
    '@keyframes dshSpin { to { transform:rotate(360deg); } }',
    '#address { box-sizing:border-box; flex:1; min-width:80px; height:28px; padding:0 11px; border:1px solid rgba(255,255,255,.16); border-radius:14px; outline:none; background:rgba(5,12,24,.24); color:inherit; font:inherit; }',
    '#address:focus { border-color:#83b7ff; box-shadow:0 0 0 2px rgba(131,183,255,.24); }',
    '#panel { position:absolute; top:56px; left:50%; transform:translateX(-50%); box-sizing:border-box; width:min(420px,calc(100vw - 24px)); max-height:320px; overflow:auto; display:none; border:1px solid rgba(255,255,255,.20); border-radius:16px; background:rgba(19,27,39,.76); backdrop-filter:blur(24px) saturate(145%); box-shadow:0 18px 42px rgba(8,15,29,.34),inset 0 1px 0 rgba(255,255,255,.12); padding:8px; color:#f0f5ff; font:13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; pointer-events:auto; }',
    '#panel.open { display:block; }',
    '#panel .save { width:auto; padding:0 12px; height:30px; border:1px solid rgba(160,200,255,.28); border-radius:8px; background:rgba(99,157,236,.16); color:#dceaff; font:13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; cursor:pointer; }',
    '#panel .item { display:flex; align-items:center; gap:8px; padding:7px 9px; border-radius:8px; cursor:pointer; }',
    '#panel .item:hover { background:rgba(255,255,255,.09); }',
    '#panel .item .t { flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
    '#panel .item .u { color:#a8c9ff; font-size:11px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; max-width:180px; }',
    '#panel .item .x { width:24px; height:24px; font:14px/1 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '.empty { padding:12px; color:#aeb9ca; font:13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '.glass-panel { position:absolute; top:68px; bottom:12px; display:none; flex-direction:column; border:1px solid rgba(255,255,255,.20); border-radius:20px; background:rgba(19,27,39,.62); backdrop-filter:blur(30px) saturate(155%); box-shadow:0 22px 54px rgba(7,14,28,.35),0 5px 16px rgba(70,122,190,.16),inset 0 1px 0 rgba(255,255,255,.12); overflow:hidden; color:#eef4ff; font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; pointer-events:auto; }',
    '#trail { right:12px; width:344px; }',
    '#trail.open, #taskPanel.open { display:flex; }',
    '#taskPanel { left:12px; width:368px; }',
    '#taskPanel .task-head, #trail .t-head { display:flex; align-items:center; justify-content:space-between; padding:11px 13px; border-bottom:1px solid rgba(255,255,255,.12); color:#f2f6ff; font:600 13px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; flex:none; }',
    '#bar #taskControl { flex:none; box-sizing:border-box; width:auto; min-width:64px; height:28px; padding:0 10px; border:1px solid rgba(151,192,255,.34); border-radius:8px; background:rgba(40,77,126,.80); box-shadow:inset 0 1px 0 rgba(255,255,255,.12); color:#e7f1ff; cursor:pointer; font:600 12px/1 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '#bar #taskControl:hover { background:rgba(60,104,166,.88); }',
    '#bar #taskControl[data-control="human"] { border-color:rgba(237,183,98,.48); background:rgba(137,88,27,.88); color:#fff0c9; }',
    '#bar #taskControl[data-control="human"]:hover { background:rgba(170,110,34,.92); }',
    '#bar #taskControl:disabled { opacity:.5; cursor:default; }',
    '#taskPanel .task-close, #trail .t-close { width:24px; height:24px; border:0; border-radius:7px; background:transparent; color:#b7c4d5; cursor:pointer; font:15px/1 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '#taskPanel .task-close:hover, #trail .t-close:hover { background:rgba(255,255,255,.13); color:#fff; }',
    '#taskList { flex:1; overflow-y:auto; padding:8px; }',
    '#taskPanel .task-row { box-sizing:border-box; width:100%; min-height:80px; display:grid; grid-template-columns:94px minmax(0,1fr); grid-template-rows:auto auto auto auto; column-gap:10px; row-gap:3px; align-items:center; padding:8px; border:1px solid transparent; border-radius:14px; background:transparent; color:#e5edf9; text-align:left; font:13px/1.35 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '#taskPanel .task-row:hover { background:rgba(255,255,255,.07); }',
    '#taskPanel .task-row:disabled { cursor:default; opacity:.48; }',
    '#taskPanel .task-row:disabled:hover { background:transparent; }',
    '#taskPanel .task-row.active { border-color:rgba(124,178,255,.62); background:rgba(85,143,224,.13); box-shadow:inset 0 1px 0 rgba(255,255,255,.06); }',
    '#taskPanel .task-thumb { grid-row:1 / 5; width:94px; height:64px; display:grid; place-items:center; overflow:hidden; border-radius:14px; background:rgba(90,116,151,.30); color:#c9dcf8; font:600 11px -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; letter-spacing:.04em; }',
    '#taskPanel .task-thumb canvas.task-thumb-canvas { display:block; width:100%; height:100%; }',
    '#taskPanel .task-title { display:flex; align-items:center; gap:7px; min-width:0; color:#f3f7ff; font-weight:600; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }',
    '#taskPanel .task-state { width:7px; height:7px; flex:none; border-radius:50%; background:#8792a1; }',
    '#taskPanel .task-row.active .task-state { background:#77d59a; }',
    '#taskPanel .task-row.status-running .task-state { background:#71b8ff; animation:dshPulse 1.1s ease-in-out infinite; }',
    '#taskPanel .task-row.status-waiting-user .task-state { background:#f0bd69; }',
    '#taskPanel .task-row.status-failed .task-state { background:#f18a8a; }',
    '@keyframes dshPulse { 50% { opacity:.42; } }',
    '#taskPanel .task-meta, #taskPanel .task-latest, #taskPanel .task-error { min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:11px; }',
    '#taskPanel .task-meta { color:#b8c5d6; }',
    '#taskPanel .task-latest { color:#acd0ff; }',
    '#taskPanel .task-error { color:#ffb1b1; }',
    '#trail #trailList { flex:1; overflow-y:auto; padding:8px 12px; }',
    '#trail .activity-day { color:#accbff; font:11px/1.4 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; text-align:center; margin:6px 0 5px; }',
    '#trail .activity-item { position:relative; display:grid; grid-template-columns:54px 16px minmax(0,1fr); column-gap:7px; align-items:start; padding:8px 0; }',
    '#trail .activity-item:hover { background:rgba(255,255,255,.045); }',
    '#trail .timeline-rail { position:relative; width:16px; min-height:30px; }',
    '#trail .timeline-rail::before { content:""; position:absolute; top:4px; bottom:-14px; left:7px; width:1px; background:rgba(181,208,245,.28); }',
    '#trail .activity-item:last-child .timeline-rail::before { display:none; }',
    '#trail .t-time { color:#a8caff; font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace; font-variant-numeric:tabular-nums; }',
    '#trail .t-flag { position:relative; z-index:1; display:grid; place-items:center; width:14px; height:14px; border-radius:50%; background:rgba(78,111,154,.72); color:#f2f7ff; font-size:9px; line-height:1; }',
    '#trail .t-flag.ok { color:#a6efbc; }',
    '#trail .t-flag.err { color:#ffb3b3; }',
    '#trail .t-text { color:#e3ebf8; word-break:break-word; font:12px/1.45 -apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",system-ui,sans-serif; }',
    '@media (hover:none) { #toolbarReveal { top:5px; transform:translateX(-50%) scale(1); opacity:1; pointer-events:auto; } }',
    '@media (max-width:760px) { #bar { width:calc(100vw - 16px); } #taskPanel { left:8px; right:8px; top:64px; bottom:auto; height:min(42vh,320px); width:auto; } #trail { left:8px; right:8px; top:auto; bottom:8px; height:min(42vh,320px); width:auto; } }',
    '</style>',
    '<div id="toolbarRevealZone"><button id="toolbarReveal" type="button" aria-label="展开工具栏" title="展开工具栏"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg></button></div>',
    '<div id="bar" role="toolbar" aria-label="DSH browser controls">',
    '<button id="back" type="button" aria-label="后退" title="后退"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></button>',
    '<button id="forward" type="button" aria-label="前进" title="前进"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18l6-6-6-6"/></svg></button>',
    '<button id="reload" type="button" aria-label="刷新" title="刷新"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-2.64-6.36"/><polyline points="21 3 21 9 15 9"/></svg></button>',
    '<button id="stop" type="button" aria-label="停止加载" title="停止加载"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="6" width="12" height="12" rx="2"/></svg></button>',
    '<button id="home" type="button" aria-label="主页" title="主页"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.75V21h14V9.75"/></svg></button>',
    '<button id="bookmarks" type="button" aria-label="收藏" title="收藏"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3.5l2.6 5.3 5.9.9-4.2 4.1 1 5.8-5.3-2.8-5.3 2.8 1-5.8-4.2-4.1 5.9-.9z"/></svg></button>',
    '<button id="trailBtn" type="button" aria-label="操作轨迹" title="操作轨迹"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></button>',
    '<button id="tasksBtn" type="button" aria-label="任务" title="任务"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="5" width="16" height="14" rx="2"/><path d="M8 9h8M8 13h5"/></svg></button>',
    '<input id="address" type="text" spellcheck="false" aria-label="地址栏" />',
    '<button id="taskControl" type="button" aria-label="接管当前任务" disabled>接管</button>',
    '<button id="toolbarHide" type="button" aria-label="收起工具栏" title="收起工具栏"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 15 6-6 6 6"/></svg></button>',
    '</div>',
    '<div id="panel" role="menu" aria-label="收藏列表">',
    '<button id="saveBookmark" class="save" type="button">★ 收藏当前页</button>',
    '<div id="bookmarkList"></div>',
    '</div>',
    '<div id="trail" class="glass-panel" role="menu" aria-label="操作轨迹">',
    '<div class="t-head"><span>操作轨迹</span><button id="trailClose" class="t-close" type="button" aria-label="关闭轨迹">×</button></div>',
    '<div id="trailList"></div>',
    '</div>',
    '<div id="taskPanel" class="glass-panel" role="menu" aria-label="浏览器任务">',
    '<div class="task-head"><span>浏览器任务</span><button id="taskClose" class="task-close" type="button" aria-label="关闭任务">×</button></div>',
    '<div id="taskList"></div>',
    '</div>',
  ].join('\n')

  return [
    '(() => {',
    '  if (window.top !== window) return',
    '',
    '  const hostId = ' + JSON.stringify(PAGE_CHROME_HOST_ID),
    '  const chromeAttribute = ' + JSON.stringify(PAGE_CHROME_ATTRIBUTE),
    '  const normalizeAddress = (' + normalizer + ')',
    '',
    '  const mount = () => {',
    '    if (document.getElementById(hostId) || !document.documentElement) return',
    "    const host = document.createElement('div')",
    '    host.id = hostId',
    "    host.setAttribute(chromeAttribute, '')",
    "    host.style.cssText = 'all:initial;position:fixed;inset:0;z-index:2147483647;pointer-events:none'",
    "    const root = host.attachShadow({ mode: 'closed' })",
    '    root.innerHTML = ' + JSON.stringify(toolbarHtml),
    '    document.documentElement.append(host)',
    '',
    "    const bar = root.getElementById('bar')",
    "    const toolbarRevealZone = root.getElementById('toolbarRevealZone')",
    "    const toolbarReveal = root.getElementById('toolbarReveal')",
    "    const toolbarHide = root.getElementById('toolbarHide')",
    "    const back = root.getElementById('back')",
    "    const forward = root.getElementById('forward')",
    "    const reload = root.getElementById('reload')",
    "    const stop = root.getElementById('stop')",
    "    const home = root.getElementById('home')",
    "    const bookmarks = root.getElementById('bookmarks')",
    "    const trail = root.getElementById('trailBtn')",
    "    const trailPanel = root.getElementById('trail')",
    "    const tasksBtn = root.getElementById('tasksBtn')",
    "    const taskPanel = root.getElementById('taskPanel')",
    "    const taskList = root.getElementById('taskList')",
    "    const taskControl = root.getElementById('taskControl')",
    "    const taskClose = root.getElementById('taskClose')",
    "    const trailList = root.getElementById('trailList')",
    "    const trailClose = root.getElementById('trailClose')",
    "    const address = root.getElementById('address')",
    "    const panel = root.getElementById('panel')",
    "    const saveBookmark = root.getElementById('saveBookmark')",
    "    const bookmarkList = root.getElementById('bookmarkList')",
    '    if (!(bar instanceof HTMLElement) || !(toolbarRevealZone instanceof HTMLElement) || !(toolbarReveal instanceof HTMLButtonElement) || !(toolbarHide instanceof HTMLButtonElement) || !(back instanceof HTMLButtonElement) || !(forward instanceof HTMLButtonElement) || !(reload instanceof HTMLButtonElement) || !(stop instanceof HTMLButtonElement) || !(home instanceof HTMLButtonElement) || !(bookmarks instanceof HTMLButtonElement) || !(address instanceof HTMLInputElement) || !(panel instanceof HTMLElement) || !(saveBookmark instanceof HTMLButtonElement) || !(bookmarkList instanceof HTMLElement) || !(trail instanceof HTMLButtonElement) || !(trailPanel instanceof HTMLElement) || !(trailList instanceof HTMLElement) || !(trailClose instanceof HTMLButtonElement) || !(tasksBtn instanceof HTMLButtonElement) || !(taskPanel instanceof HTMLElement) || !(taskList instanceof HTMLElement) || !(taskControl instanceof HTMLButtonElement) || !(taskClose instanceof HTMLButtonElement)) return',
    '',
    "    const refreshAddress = () => { if (root.activeElement !== address) address.value = location.href }",
    "    const navigate = () => { const target = normalizeAddress(address.value); if (target !== '') location.assign(target) }",
    "    const bookmarksKey = 'dsh-chrome-bookmarks'",
    "    const loadBookmarks = () => { try { const v = JSON.parse(localStorage.getItem(bookmarksKey) || '[]'); return Array.isArray(v) ? v : [] } catch { return [] } }",
    '    const saveBookmarks = (list) => { try { localStorage.setItem(bookmarksKey, JSON.stringify(list)) } catch { /* quota */ } }',
    '    const renderBookmarks = () => {',
    '      const list = loadBookmarks()',
    "      bookmarkList.textContent = ''",
    "      if (list.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无收藏'; bookmarkList.append(empty); return }",
    '      for (const item of list) {',
    "        const row = document.createElement('div')",
    "        row.className = 'item'",
    "        const t = document.createElement('span'); t.className = 't'; t.textContent = item.title || item.url",
    "        const u = document.createElement('span'); u.className = 'u'; u.textContent = item.url",
    "        const x = document.createElement('button'); x.className = 'x'; x.type = 'button'; x.textContent = '×'; x.title = '删除收藏'",
    "        x.addEventListener('click', event => { event.stopPropagation(); saveBookmarks(loadBookmarks().filter(b => b.url !== item.url)); renderBookmarks(); updateBookmarkStar() })",
    "        row.addEventListener('click', () => { panel.classList.remove('open'); location.assign(item.url) })",
    '        row.append(t, u, x)',
    '        bookmarkList.append(row)',
    '      }',
    '    }',
    "    const starSvg = bookmarks.querySelector('svg')",
    "    const updateBookmarkStar = () => { if (starSvg) starSvg.setAttribute('fill', loadBookmarks().some(b => b.url === location.href) ? 'currentColor' : 'none') }",
    "    const spinReload = () => { reload.classList.add('spinning'); window.setTimeout(() => reload.classList.remove('spinning'), 500) }",
    "    const fmtTime = (at) => { const d = new Date(Number(at) || Date.now()); return String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0') + ':' + String(d.getSeconds()).padStart(2, '0') }",
    "    const fmtDate = (at) => { const d = new Date(Number(at) || Date.now()); return (d.getMonth() + 1) + '/' + d.getDate() }",
    "    const describe = (entry) => {",
    "      const p = entry.params || {}",
    "      switch (entry.action) {",
    "        case 'navigate': return '导航到 ' + String(p.url || '').slice(0, 80)",
    "        case 'click': return '点击 (' + p.x + ', ' + p.y + ')'",
    "        case 'fill': return '填写表单 ' + (Array.isArray(p.fields) ? p.fields.length : p.fields ?? 1) + ' 项'",
    "        case 'type': return '输入文字' + (p.text ? '（' + String(p.text).slice(0, 20) + '…）' : '')",
    "        case 'execute': return '执行页面脚本'",
    "        case 'screenshot': return '截图' + (p.fullPage ? '（整页）' : '')",
    "        case 'download': return '下载 ' + String(p.savePath || p.url || '').slice(0, 60)",
    "        case 'content': return '读取页面内容' + (p.selector ? '（' + p.selector + '）' : '')",
    "        case 'snapshot': return '页面快照'",
    "        default: return String(entry.action || '')",
    "      }",
    "    }",
    "    const renderTrail = () => {",
    "      const list = Array.isArray(window.__dshTrail) ? window.__dshTrail : []",
    "      trailList.textContent = ''",
    "      if (list.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无操作记录'; trailList.append(empty); return }",
    "      const items = [...list].reverse()",
    "      let lastDay = ''",
    "      for (const entry of items) {",
    "        const day = fmtDate(entry.at)",
    "        if (day !== lastDay) {",
    "          const head = document.createElement('div'); head.className = 'activity-day'; head.dataset.dshTrailDay = day; head.textContent = '— ' + day + ' —'; trailList.append(head); lastDay = day",
    "        }",
    "        const row = document.createElement('div')",
    "        row.className = 'activity-item'",
    "        const time = document.createElement('span'); time.className = 't-time'; time.textContent = fmtTime(entry.at)",
    "        const rail = document.createElement('div'); rail.className = 'timeline-rail'",
    "        const flag = document.createElement('span'); flag.className = 't-flag ' + (entry.ok === false ? 'err' : 'ok'); flag.textContent = entry.ok === false ? '✗' : '✓'",
    "        rail.append(flag)",
    "        const text = document.createElement('span'); text.className = 't-text'; text.textContent = describe(entry)",
    "        row.append(time, rail, text)",
    "        trailList.append(row)",
    "      }",
    "    }",
    "    window.__dshTrailRender = renderTrail",
    "    const appendTrailEntry = entry => {",
    "      if (!trailPanel.classList.contains('open')) return",
    "      if (!entry || typeof entry !== 'object') return",
    "      if (trailList.childElementCount === 0 || trailList.querySelector('.empty')) { renderTrail(); return }",
    "      const atTop = trailList.scrollTop <= 4",
    "      const previousHeight = trailList.scrollHeight",
    "      const day = fmtDate(entry.at)",
    "      const row = document.createElement('div')",
    "      row.className = 'activity-item'",
    "      const time = document.createElement('span'); time.className = 't-time'; time.textContent = fmtTime(entry.at)",
    "      const rail = document.createElement('div'); rail.className = 'timeline-rail'",
    "      const flag = document.createElement('span'); flag.className = 't-flag ' + (entry.ok === false ? 'err' : 'ok'); flag.textContent = entry.ok === false ? '✗' : '✓'",
    "      rail.append(flag)",
    "      const text = document.createElement('span'); text.className = 't-text'; text.textContent = describe(entry)",
    "      row.append(time, rail, text)",
    "      const first = trailList.firstElementChild",
    "      if (first && first instanceof HTMLElement && first.dataset.dshTrailDay === day) first.after(row)",
    "      else { const head = document.createElement('div'); head.className = 'activity-day'; head.dataset.dshTrailDay = day; head.textContent = '— ' + day + ' —'; trailList.prepend(row); trailList.prepend(head) }",
    "      if (!atTop) trailList.scrollTop += trailList.scrollHeight - previousHeight",
    "    }",
    "    const emitTaskAction = taskKey => { try { const binding = window.__dshBrowserTaskAction; if (typeof binding === 'function') binding(JSON.stringify({ type: 'switch-task', taskKey })) } catch { /* host unavailable */ } }",
    "    const emitTaskControl = (taskKey, control) => { try { const binding = window.__dshBrowserTaskAction; if (typeof binding === 'function') binding(JSON.stringify({ type: 'set-control-owner', taskKey, control })) } catch { /* host unavailable */ } }",
    "    const emitWorkspacePanels = (tasks, trail) => { try { const binding = window.__dshBrowserTaskAction; if (typeof binding === 'function') binding(JSON.stringify({ type: 'set-workspace-panels', tasks, trail })) } catch { /* host unavailable */ } }",
    "    const latestText = latest => { if (!latest || typeof latest !== 'object') return ''; const action = String(latest.action || ''); return action === '' ? '' : action + (latest.at ? ' · ' + fmtTime(latest.at) : '') }",
    "    const statusText = status => status === 'running' ? '执行中' : status === 'waiting-user' ? '等待用户' : status === 'failed' ? '失败' : '空闲'",
    '    let activeTask = null',
    '    let userControlRequested = false',
    '    const renderTaskControl = tasks => {',
    "      activeTask = tasks.find(task => task && task.active === true) || null",
    "      if (!activeTask || typeof activeTask.key !== 'string') { userControlRequested = false; taskControl.disabled = true; taskControl.textContent = '接管'; taskControl.removeAttribute('data-control'); return }",
    "      const human = activeTask.control === 'human'",
    "      if (!human) userControlRequested = false",
    "      taskControl.disabled = false; taskControl.dataset.control = human ? 'human' : 'agent'; taskControl.textContent = human ? '交还 Agent' : '接管'; taskControl.setAttribute('aria-label', human ? '交还当前任务给 Agent' : '接管当前任务')",
    '    }',
    "    const paintTaskThumbnail = (thumb, task, taskKey) => {",
    "      const source = typeof task.thumbnail === 'string' ? task.thumbnail : ''",
    "      const version = String(Number.isFinite(task.thumbnailVersion) ? task.thumbnailVersion : 0)",
    "      const token = taskKey + ':' + version + ':' + source.length",
    "      if (thumb.dataset.dshThumbnailToken === token) return",
    "      thumb.dataset.dshThumbnailToken = token",
    "      const origin = typeof task.url === 'string' ? task.url.replace(/^https?:\\/\\//, '') : ''",
    "      thumb.textContent = origin === '' ? 'DSH' : origin.toUpperCase().slice(0, 2)",
    "      if (!source.startsWith('data:image/jpeg;base64,') || typeof createImageBitmap !== 'function') return",
    "      try {",
    "        const payload = source.slice('data:image/jpeg;base64,'.length)",
    "        const bytes = Uint8Array.from(atob(payload), ch => ch.charCodeAt(0))",
    "        const blob = new Blob([bytes], { type: 'image/jpeg' })",
    "        createImageBitmap(blob).then(bitmap => {",
    "          const canvas = document.createElement('canvas')",
    "          canvas.className = 'task-thumb-canvas'",
    "          canvas.width = 188",
    "          canvas.height = 128",
    "          const ctx = canvas.getContext('2d')",
    "          if (!ctx) { if (typeof bitmap.close === 'function') bitmap.close(); return }",
    "          const scale = Math.max(canvas.width / bitmap.width, canvas.height / bitmap.height)",
    "          const drawnWidth = bitmap.width * scale",
    "          const drawnHeight = bitmap.height * scale",
    "          ctx.drawImage(bitmap, (canvas.width - drawnWidth) / 2, (canvas.height - drawnHeight) / 2, drawnWidth, drawnHeight)",
    "          if (typeof bitmap.close === 'function') bitmap.close()",
    "          if (thumb.isConnected && thumb.dataset.dshThumbnailToken === token) { thumb.textContent = ''; thumb.append(canvas) }",
    "        }).catch(() => { /* decode failure keeps fallback */ })",
    "      } catch { /* malformed payload keeps fallback */ }",
    "    }",
    "    const renderTasks = () => {",
    "      const tasks = Array.isArray(window.__dshTasks) ? window.__dshTasks : []",
    '      renderTaskControl(tasks)',
    "      taskList.textContent = ''",
    "      if (tasks.length === 0) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = '暂无浏览器任务'; taskList.append(empty); return }",
    "      for (const task of tasks) {",
    "        if (!task || typeof task !== 'object') continue",
    "        const taskKey = typeof task.key === 'string' && task.key.trim() !== '' ? task.key : undefined",
    "        const status = ['idle', 'running', 'waiting-user', 'failed'].includes(task.status) ? task.status : 'idle'",
    "        const control = task.control === 'human' ? 'human' : 'agent'",
    "        const row = document.createElement('button'); row.type = 'button'; row.className = 'task-row status-' + status + (task.active ? ' active' : ''); row.disabled = taskKey === undefined; row.dataset.dshTaskKey = taskKey || ''; row.dataset.dshThumbnailVersion = String(Number.isFinite(task.thumbnailVersion) ? task.thumbnailVersion : 0)",
    "        const thumb = document.createElement('div'); thumb.className = 'task-thumb'; thumb.dataset.dshTaskThumb = '1'; paintTaskThumbnail(thumb, task, taskKey || ''); const source = ''",
    "        const origin = typeof task.url === 'string' ? task.url.replace(/^https?:\\/\\//, '') : ''",
    "        thumb.textContent = origin === '' ? 'DSH' : origin.toUpperCase().slice(0, 2)",
    "        if (source.startsWith('data:image/jpeg;base64,') && typeof createImageBitmap === 'function') {",
    "          try {",
    "            const payload = source.slice('data:image/jpeg;base64,'.length)",
    "            const bytes = Uint8Array.from(atob(payload), ch => ch.charCodeAt(0))",
    "            const blob = new Blob([bytes], { type: 'image/jpeg' })",
    "            createImageBitmap(blob).then(bitmap => {",
    "              const canvas = document.createElement('canvas')",
    "              canvas.className = 'task-thumb-canvas'",
    "              canvas.width = 188",
    "              canvas.height = 128",
    "              const ctx = canvas.getContext('2d')",
    "              if (!ctx) {",
    "                if (typeof bitmap.close === 'function') bitmap.close()",
    "                return",
    "              }",
    "              const scale = Math.max(canvas.width / bitmap.width, canvas.height / bitmap.height)",
    "              const drawnWidth = bitmap.width * scale",
    "              const drawnHeight = bitmap.height * scale",
    "              ctx.drawImage(bitmap, (canvas.width - drawnWidth) / 2, (canvas.height - drawnHeight) / 2, drawnWidth, drawnHeight)",
    "              if (typeof bitmap.close === 'function') bitmap.close()",
    "              if (thumb.isConnected) { thumb.textContent = ''; thumb.append(canvas) }",
    "            }).catch(() => { /* async decode failure keeps the origin/DSH fallback */ })",
    "          } catch { /* malformed payload keeps the origin/DSH fallback */ }",
    "        }",
    "        const title = document.createElement('span'); title.className = 'task-title'",
    "        const state = document.createElement('span'); state.className = 'task-state'; state.dataset.dshTaskState = '1'; state.setAttribute('aria-label', statusText(status) + (task.active ? '，当前任务' : '，后台任务'))",
    "        const label = document.createElement('span'); label.dataset.dshTaskLabel = '1'; label.textContent = (typeof task.label === 'string' && task.label !== '' ? task.label : (taskKey === undefined ? '未命名任务' : taskKey.slice(0, 12)))",
    "        title.append(state, label)",
    "        const meta = document.createElement('span'); meta.className = 'task-meta'; meta.dataset.dshTaskMeta = '1'; meta.textContent = statusText(status) + ' · ' + (control === 'human' ? '用户接管' : 'Agent 控制') + ' · ' + (Number.isFinite(task.tabs) ? task.tabs : 0) + ' 个标签页' + (typeof task.url === 'string' && task.url !== '' ? ' · ' + task.url : '')",
    "        const recent = document.createElement('span'); recent.className = 'task-latest'; recent.dataset.dshTaskLatest = '1'; recent.textContent = latestText(task.latest)",
    "        const failure = document.createElement('span'); failure.className = 'task-error'; failure.dataset.dshTaskError = '1'; failure.textContent = typeof task.error === 'string' ? task.error : ''",
    "        row.append(thumb, title, meta, recent, failure)",
    "        if (taskKey !== undefined) row.addEventListener('click', () => emitTaskAction(taskKey))",
    "        taskList.append(row)",
    "      }",
    "    }",
    "    window.__dshTaskRender = renderTasks",
    "    const patchTaskRow = task => {",
    "      if (!task || typeof task !== 'object' || typeof task.key !== 'string') return false",
    "      const row = [...taskList.children].find(candidate => candidate instanceof HTMLElement && candidate.dataset.dshTaskKey === task.key)",
    "      if (!(row instanceof HTMLButtonElement)) return false",
    "      const version = String(Number.isFinite(task.thumbnailVersion) ? task.thumbnailVersion : 0)",
    "      if (row.dataset.dshThumbnailVersion !== version) return false",
    "      const status = ['idle', 'running', 'waiting-user', 'failed'].includes(task.status) ? task.status : 'idle'",
    "      const control = task.control === 'human' ? 'human' : 'agent'",
    "      row.className = 'task-row status-' + status + (task.active ? ' active' : '')",
    "      row.disabled = false",
    "      const state = row.querySelector('[data-dsh-task-state]')",
    "      if (state instanceof HTMLElement) state.setAttribute('aria-label', statusText(status) + (task.active ? '，当前任务' : '，后台任务'))",
    "      const label = row.querySelector('[data-dsh-task-label]')",
    "      if (label instanceof HTMLElement) label.textContent = typeof task.label === 'string' && task.label !== '' ? task.label : task.key.slice(0, 12)",
    "      const meta = row.querySelector('[data-dsh-task-meta]')",
    "      if (meta instanceof HTMLElement) meta.textContent = statusText(status) + ' · ' + (control === 'human' ? '用户接管' : 'Agent 控制') + ' · ' + (Number.isFinite(task.tabs) ? task.tabs : 0) + ' 个标签页' + (typeof task.url === 'string' && task.url !== '' ? ' · ' + task.url : '')",
    "      const recent = row.querySelector('[data-dsh-task-latest]')",
    "      if (recent instanceof HTMLElement) recent.textContent = latestText(task.latest)",
    "      const failure = row.querySelector('[data-dsh-task-error]')",
    "      if (failure instanceof HTMLElement) failure.textContent = typeof task.error === 'string' ? task.error : ''",
    "      return true",
    "    }",
    "    const applyWorkspacePanels = () => {",
    "      const state = window.__dshWorkspacePanels && typeof window.__dshWorkspacePanels === 'object' ? window.__dshWorkspacePanels : {}",
    "      const tasksOpen = state.tasks === true",
    "      const trailOpen = state.trail === true",
    "      taskPanel.classList.toggle('open', tasksOpen)",
    "      trailPanel.classList.toggle('open', trailOpen)",
    "      if (tasksOpen || trailOpen) { bar.classList.add('open'); toolbarRevealZone.classList.remove('armed') }",
    "    }",
    "    const syncWorkspacePanels = () => { const tasksOpen = taskPanel.classList.contains('open'); const trailOpen = trailPanel.classList.contains('open'); emitWorkspacePanels(tasksOpen, trailOpen) }",
    "    const armToolbarReveal = () => { if (!bar.classList.contains('open')) toolbarRevealZone.classList.add('armed') }",
    "    const disarmToolbarReveal = () => { if (!bar.classList.contains('open') && root.activeElement !== toolbarReveal) toolbarRevealZone.classList.remove('armed') }",
    "    const isToolbarTriggerPosition = event => event.clientY <= 56 && Math.abs(event.clientX - window.innerWidth / 2) <= 140",
    "    const trackToolbarReveal = event => { if (!event.isTrusted || bar.classList.contains('open')) return; if (isToolbarTriggerPosition(event)) armToolbarReveal(); else disarmToolbarReveal() }",
    "    const triggerToolbarFromPage = event => {",
    "      if (!event.isTrusted || bar.classList.contains('open') || event.button !== 0 || !isToolbarTriggerPosition(event)) return",
    "      event.preventDefault()",
    "      event.stopImmediatePropagation()",
    "      openToolbar()",
    "    }",
    "    const openToolbar = () => { bar.classList.add('open'); toolbarRevealZone.classList.remove('armed') }",
    "    const closeToolbar = () => {",
    "      bar.classList.remove('open')",
    "      panel.classList.remove('open')",
    "      trailPanel.classList.remove('open')",
    "      taskPanel.classList.remove('open')",
    "      syncWorkspacePanels()",
    "      toolbarRevealZone.classList.add('armed')",
    "      toolbarReveal.focus()",
    "    }",
    "    window.__dshWorkspaceRender = applyWorkspacePanels",
    "    let chromeEpoch = -1",
    "    let chromeRevision = -1",
    "    let chromeSelectedTaskKey = undefined",
    "    const requestChromeBootstrap = () => { try { const binding = window.__dshBrowserTaskAction; if (typeof binding === 'function') binding(JSON.stringify({ type: 'request-chrome-bootstrap' })) } catch { /* host unavailable */ } }",
    "    const applyChromeMessage = message => {",
    "      if (!message || typeof message !== 'object') return",
    "      if (message.kind === 'bootstrap') {",
    "        chromeEpoch = Number(message.epoch)",
    "        chromeRevision = Number(message.revision)",
    "        chromeSelectedTaskKey = typeof message.selectedTaskKey === 'string' ? message.selectedTaskKey : undefined",
    "        window.__dshTasks = Array.isArray(message.tasks) ? message.tasks : []",
    "        window.__dshTrail = Array.isArray(message.trail) ? message.trail : []",
    "        window.__dshWorkspacePanels = message.panels && typeof message.panels === 'object' ? message.panels : { tasks: false, trail: false }",
    "        renderTasks()",
    "        renderTrail()",
    "        applyWorkspacePanels()",
    "        return",
    "      }",
    "      if (message.kind !== 'patch') return",
    "      if (Number(message.epoch) !== chromeEpoch || Number(message.revision) !== chromeRevision + 1) { requestChromeBootstrap(); return }",
    "      chromeRevision = Number(message.revision)",
    "      const tasks = Array.isArray(window.__dshTasks) ? [...window.__dshTasks] : []",
    "      let fullTaskRender = false",
    "      const taskPatches = []",
    "      let trailReplaced = false",
    "      const trailAppends = []",
    "      let panelsChanged = false",
    "      for (const operation of Array.isArray(message.operations) ? message.operations : []) {",
    "        if (!operation || typeof operation !== 'object') continue",
    "        if (operation.op === 'task.upsert' && operation.task && typeof operation.task.key === 'string') {",
    "          const index = tasks.findIndex(task => task && task.key === operation.task.key)",
    "          if (index >= 0) { tasks[index] = operation.task; taskPatches.push(operation.task) }",
    "          else { tasks.push(operation.task); fullTaskRender = true }",
    "        } else if (operation.op === 'task.remove' && typeof operation.key === 'string') {",
    "          const index = tasks.findIndex(task => task && task.key === operation.key)",
    "          if (index >= 0) { tasks.splice(index, 1); fullTaskRender = true }",
    "        } else if (operation.op === 'task.active') {",
    "          chromeSelectedTaskKey = typeof operation.key === 'string' ? operation.key : undefined",
    "          for (const task of tasks) if (task && typeof task === 'object') task.active = task.key === chromeSelectedTaskKey",
    "          fullTaskRender = true",
    "        } else if (operation.op === 'task.thumbnail' && typeof operation.key === 'string') {",
    "          const task = tasks.find(candidate => candidate && candidate.key === operation.key)",
    "          if (task) { task.thumbnail = operation.dataUrl; task.thumbnailVersion = operation.version; fullTaskRender = true }",
    "        } else if (operation.op === 'trail.append' && operation.taskKey === chromeSelectedTaskKey && operation.entry) {",
    "          const trail = Array.isArray(window.__dshTrail) ? window.__dshTrail : []",
    "          window.__dshTrail = [...trail, operation.entry]",
    "          trailAppends.push(operation.entry)",
    "        } else if (operation.op === 'trail.replace' && (operation.taskKey === chromeSelectedTaskKey || operation.taskKey === undefined)) {",
    "          window.__dshTrail = Array.isArray(operation.entries) ? operation.entries : []",
    "          trailReplaced = true",
    "        } else if (operation.op === 'panels.set' && operation.panels && typeof operation.panels === 'object') {",
    "          window.__dshWorkspacePanels = operation.panels",
    "          panelsChanged = true",
    "        }",
    "      }",
    "      window.__dshTasks = tasks",
    "      if (fullTaskRender) renderTasks()",
    "      else if (taskPatches.length > 0) { renderTaskControl(tasks); for (const task of taskPatches) { if (!patchTaskRow(task)) { renderTasks(); break } } }",
    "      if (trailReplaced) renderTrail()",
    "      else for (const entry of trailAppends) appendTrailEntry(entry)",
    "      if (panelsChanged) applyWorkspacePanels()",
    "    }",
    "    window.__dshChromeApply = applyChromeMessage",
    "    if (window.__dshChromeBootstrap) applyChromeMessage(window.__dshChromeBootstrap)",
    "    const toggleTrail = () => { const open = trailPanel.classList.toggle('open'); if (open) { panel.classList.remove('open'); renderTrail() } syncWorkspacePanels() }",
    "    const closeTrail = () => { trailPanel.classList.remove('open'); syncWorkspacePanels() }",
    "    const toggleTasks = () => { const open = taskPanel.classList.toggle('open'); if (open) { panel.classList.remove('open'); renderTasks() } syncWorkspacePanels() }",
    "    const closeTasks = () => { taskPanel.classList.remove('open'); syncWorkspacePanels() }",
    "    const togglePanel = () => { const open = panel.classList.toggle('open'); if (open) { trailPanel.classList.remove('open'); taskPanel.classList.remove('open'); renderBookmarks(); updateBookmarkStar(); syncWorkspacePanels() } }",
    "    applyWorkspacePanels()",
    '',
    "    toolbarRevealZone.addEventListener('pointerenter', armToolbarReveal)",
    "    toolbarRevealZone.addEventListener('pointerleave', disarmToolbarReveal)",
    "    toolbarRevealZone.addEventListener('mouseenter', armToolbarReveal)",
    "    toolbarRevealZone.addEventListener('mouseleave', disarmToolbarReveal)",
    "    window.addEventListener('pointermove', trackToolbarReveal, true)",
    "    window.addEventListener('mousemove', trackToolbarReveal, true)",
    "    window.addEventListener('pointerdown', triggerToolbarFromPage, true)",
    "    window.addEventListener('mousedown', triggerToolbarFromPage, true)",
    "    toolbarReveal.addEventListener('focus', armToolbarReveal)",
    "    toolbarReveal.addEventListener('blur', () => window.setTimeout(disarmToolbarReveal, 0))",
    "    toolbarReveal.addEventListener('click', openToolbar)",
    "    toolbarHide.addEventListener('click', closeToolbar)",
    "    back.addEventListener('click', () => history.back())",
    "    forward.addEventListener('click', () => history.forward())",
    "    reload.addEventListener('click', () => { spinReload(); location.reload() })",
    "    stop.addEventListener('click', () => window.stop())",
    "    home.addEventListener('click', () => location.assign('https://www.bing.com'))",
    "    bookmarks.addEventListener('click', togglePanel)",
    "    trail.addEventListener('click', toggleTrail)",
    "    trailClose.addEventListener('click', closeTrail)",
    "    tasksBtn.addEventListener('click', toggleTasks)",
    "    taskClose.addEventListener('click', closeTasks)",
    "    const toggleTaskControl = () => { if (activeTask && typeof activeTask.key === 'string') emitTaskControl(activeTask.key, activeTask.control === 'human' ? 'agent' : 'human') }",
    "    taskControl.addEventListener('pointerdown', event => { if (event.button === 0) toggleTaskControl() })",
    "    taskControl.addEventListener('click', event => { if (event.detail === 0) toggleTaskControl() })",
    "    saveBookmark.addEventListener('click', () => {",
    '      const list = loadBookmarks().filter(b => b.url !== location.href)',
    "      list.unshift({ url: location.href, title: document.title || location.href })",
    '      saveBookmarks(list)',
    '      renderBookmarks()',
    '      updateBookmarkStar()',
    '    })',
    "    address.addEventListener('keydown', event => {",
    "      if (event.key === 'Enter') { event.preventDefault(); navigate() }",
    "      else if (event.key === 'Escape') address.blur()",
    '    })',
    "    window.addEventListener('keydown', event => {",
    "      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'l') { event.preventDefault(); address.focus(); address.select() }",
    '    }, true)',
    "    window.addEventListener('popstate', refreshAddress)",
    "    window.addEventListener('hashchange', refreshAddress)",
    '',
    "    // User-control signal: mark the host so model-facing snapshots can tell",
    "    // that a human is driving this page right now (ego's handoff semantics).",
    "    let lastUserActivity = 0",
    "    let chromePageActive = window.__dshChromeActive !== false",
    "    let userActivityTimer = 0",
    "    let addressTimer = 0",
    "    const stopChromeTimers = () => { if (userActivityTimer !== 0) { window.clearInterval(userActivityTimer); userActivityTimer = 0 } if (addressTimer !== 0) { window.clearInterval(addressTimer); addressTimer = 0 } }",
    "    const startChromeTimers = () => {",
    "      if (!chromePageActive) return",
    "      refreshAddress()",
    "      if (userActivityTimer === 0) userActivityTimer = window.setInterval(() => { if (lastUserActivity !== 0 && Date.now() - lastUserActivity > 60000) host.removeAttribute('data-dsh-user-active') }, 15000)",
    "      if (addressTimer === 0) addressTimer = window.setInterval(refreshAddress, 750)",
    "    }",
    "    const setChromeActive = active => { chromePageActive = active === true; stopChromeTimers(); if (chromePageActive) startChromeTimers() }",
    "    window.__dshChromeSetActive = setChromeActive",
    "    const markUserActive = () => { lastUserActivity = Date.now(); host.setAttribute('data-dsh-user-active', '1') }",
    "    const agentInputSuppressed = () => Number(host.getAttribute('data-dsh-agent-input-until') || '0') > Date.now()",
    "    const isChromeEvent = event => event.target === host || event.composedPath().includes(host)",
    "    const isEditableTarget = target => target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement || (target instanceof HTMLElement && target.isContentEditable)",
    "    const isScrollKey = event => ['ArrowUp', 'ArrowDown', 'PageUp', 'PageDown', 'Home', 'End', ' '].includes(event.key) && !isEditableTarget(event.target)",
    "    const isScrollbarPointer = event => event.clientX >= document.documentElement.clientWidth || event.clientY >= document.documentElement.clientHeight",
    "    const canTrackUserEvent = event => event.isTrusted && !isChromeEvent(event) && !agentInputSuppressed()",
    "    const requestUserControl = () => { if (userControlRequested || !activeTask || typeof activeTask.key !== 'string' || activeTask.control === 'human') return; userControlRequested = true; markUserActive(); emitTaskControl(activeTask.key, 'human') }",
    "    let pointerCandidate = null",
    "    const beginPointerCandidate = (id, event) => { if (!canTrackUserEvent(event) || isScrollbarPointer(event)) return; pointerCandidate = { id, x: event.clientX, y: event.clientY, moved: false } }",
    "    const movePointerCandidate = (id, event) => { if (!pointerCandidate || pointerCandidate.id !== id) return; if (Math.hypot(event.clientX - pointerCandidate.x, event.clientY - pointerCandidate.y) > 8) pointerCandidate.moved = true }",
    "    const finishPointerCandidate = (id, event) => { const candidate = pointerCandidate; pointerCandidate = null; if (!candidate || candidate.id !== id || candidate.moved || !canTrackUserEvent(event)) return; requestUserControl() }",
    "    window.addEventListener('pointerdown', event => beginPointerCandidate(event.pointerId, event), true)",
    "    window.addEventListener('pointermove', event => movePointerCandidate(event.pointerId, event), true)",
    "    window.addEventListener('pointerup', event => finishPointerCandidate(event.pointerId, event), true)",
    "    window.addEventListener('pointercancel', () => { pointerCandidate = null }, true)",
    "    // Electron CDP emits Mouse Events for some input paths without Pointer Events.",
    "    window.addEventListener('mousedown', event => { if (pointerCandidate === null) beginPointerCandidate('mouse', event) }, true)",
    "    window.addEventListener('mousemove', event => movePointerCandidate('mouse', event), true)",
    "    window.addEventListener('mouseup', event => finishPointerCandidate('mouse', event), true)",
    "    window.addEventListener('keydown', event => { if (!canTrackUserEvent(event) || isScrollKey(event)) return; requestUserControl() }, true)",
    "    // No wheel listener is intentional: scrolling never changes ownership.",
    '',
    '    setChromeActive(chromePageActive)',
    "    host.setAttribute('data-dsh-browser-ready', '1')",
    '  }',
    '',
    "  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount, { once: true })",
    '  else mount()',
    '})()',
  ].join('\n')
}
